security:
    providers:
        administrators:
            entity: { class: AppBundle:Usuarios, property: usuario }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check

    access_control:
        - { path: ^/client, roles: ROLE_USER }

    encoders:
        AppBundle\Entity\Usuarios: plaintext
